name: Update README
on:
  schedule:
    - cron: "26 6 1-25 12 *" # from the 1. December till 25. December every day at 6:26am (avoid load at full hours)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 2284826
          sessionCookie: ${{ secrets.AOC_SESSION }}
          starSymbol: 🌟
      - uses: stefanzweifel/git-auto-commit-action@v5 
        with:
          commit_message: Update README stars